version: '3.8'

services:
  frontend:
    container_name: frontend 
    build:
      context: ./todolist./public
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: backend 
    build:
      context: ./Server
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    container_name: mongo 
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
