version: '3.8'

services:
  frontend:
    image: node:14
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm install axios react-icons && npm run dev"
    depends_on:
      - backend

  backend:
    image: node:14
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: sh -c "npm install && npm install express mongoose cors && npm install nodemon && nodemon index.js"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
